all:
	gcc -I../ hello.c ../sm.c -o hello
	gcc -I../ simple_client.c ../sm.c -o simple_client
	gcc -I../ share.c ../sm.c -o share
	gcc -I../ matmul.c ../sm.c -o matmul
	gcc -I../ matmul.c ../sm.c -o matmul
	gcc -I../ tcp_server.c ../sm_socket.c -o tcp_server
	gcc -I../ tcp_client.c ../sm_socket.c -o tcp_client
